image: alekzonder/puppeteer

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - yarn
            - yarn lint
            - yarn tsc
            - yarn build
            - yarn deploy
