name: Deploy Latest Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - run: bun install --frozen-lockfile
      - run: bun run audit
      - run: bun run lint
      - run: bun run tsc
      - run: bun run test
      - run: bun run build
